# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info257proj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BowenTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverydate', models.CharField(blank=True, max_length=100, null=True)),
                ('hourending', models.CharField(blank=True, max_length=100, null=True)),
                ('busname', models.CharField(blank=True, max_length=100, null=True)),
                ('lmp', models.FloatField(blank=True, null=True)),
                ('dstflag', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Bowen_Test',
            },
        ),
    ]
